using System.IO;
using UnityEditor;
using UnityEngine;

public class TagEnumGenerator : MonoBehaviour
{
    private const string enumFilePath = "Assets/02.Scripts/02-20. Util/Tags.cs";

    [MenuItem("Tools/Generate Tag Enum")]
    public static void GenerateTagEnum()
    {
        if (!Directory.Exists("Assets/02.Scripts/02-20. Util"))
        {
            Directory.CreateDirectory("Assets/02.Scripts/02-20. Util");
        }
        string[] tags = UnityEditorInternal.InternalEditorUtility.tags;
        using (StreamWriter writer = new StreamWriter(enumFilePath))
        {
            writer.WriteLine("// Auto-generated by TagEnumGenerator");
            writer.WriteLine("public enum Tags");
            writer.WriteLine("{");

            foreach (string tag in tags)
            {
                writer.WriteLine($"{tag.Replace(" ", "_")},");
            }

            writer.WriteLine("}");
        }
        AssetDatabase.Refresh();
    }
}
